### ISSUE TITLE
dapp loops trying to connect to wallet

### ISSUE THREAD

**Issue by dckc** [Agoric/dapp-fungible-faucet#58]
## To Reproduce

1. git clone https://github.com/Agoric/dapp-fungible-faucet
2. git checkout fix-lockdown (2023-04-03 15:46 729d399 fix: fix lockdown)
3. check out any version of agoric-sdk; yarn; yarn build; yarn link-cli ~/.local/bin/agoric
4. `agoric install` in dapp-fungible-faucet
5. `agoric start`
6. `agoric deploy contract/deploy.js api/deploy.js`
7. `yarn start` in `ui` after deploy is done
8. Agoric wallet: error

expected: dapp connects to the wallet

perhaps useful: `agoric open --repl`

**Comment by dckc** [comment]
```

warn @ lockdown.umd.js:6540
visitProperties @ lockdown.umd.js:8576
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
whitelistIntrinsics @ lockdown.umd.js:8605
repairIntrinsics @ lockdown.umd.js:8948
lockdown @ lockdown.umd.js:9025
(anonymous) @ bridge.html:1
lockdown.umd.js:6540 lockdown done.
lockdown.umd.js:6540 {connectionState: 'disconnected', schemaActions: null, services: null, setConnectionState: ƒ, setBackend: ƒ, …}
logo.svg:1          GET https://agoric.com/wp-content/themes/agoric_2021_theme/assets/img/logo.svg 404
Image (async)
z @ VM36 main.eed1f954.js:75
es @ VM36 main.eed1f954.js:75
vl @ VM36 main.eed1f954.js:75
ml @ VM36 main.eed1f954.js:75
hl @ VM36 main.eed1f954.js:75
sl @ VM36 main.eed1f954.js:75
nl @ VM36 main.eed1f954.js:75
Zl @ VM36 main.eed1f954.js:75
(anonymous) @ VM36 main.eed1f954.js:75
cl @ VM36 main.eed1f954.js:75
Yl @ VM36 main.eed1f954.js:75
t.render @ VM36 main.eed1f954.js:75
(anonymous) @ VM36 main.eed1f954.js:102
(anonymous) @ VM36 main.eed1f954.js:102
(anonymous) @ VM36 main.eed1f954.js:102
ses.umd.js:6702 connecting error CustomEvent {isTrusted: false, detail: {…}, type: 'error', target: agoric-iframe-messenger, currentTarget: agoric-iframe-messenger, …}
ses.umd.js:6702 error {state: 'error', walletConnection: Alleged: WalletConnection, cache: ƒ}
DevTools failed to load source map: Could not load content for chrome-extension://dmkamcknogkgcdfhhbddcghachkejeap/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
ses.umd.js:6702 locating locate CustomEvent {isTrusted: false, detail: {…}, type: 'message', target: agoric-iframe-messenger, currentTarget: agoric-iframe-messenger, …}
DevTools failed to load source map: Could not load content for chrome-extension://dmkamcknogkgcdfhhbddcghachkejeap/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
lockdown.umd.js:6540 Removing intrinsics.%ArrayPrototype%.toReversed
warn @ lockdown.umd.js:6540
visitProperties @ lockdown.umd.js:8576
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
whitelistIntrinsics @ lockdown.umd.js:8605
repairIntrinsics @ lockdown.umd.js:8948
lockdown @ lockdown.umd.js:9025
(anonymous) @ bridge.html?suggestedDappPetname=FungibleFaucet:1
lockdown.umd.js:6540 Removing intrinsics.%ArrayPrototype%.toSorted
warn @ lockdown.umd.js:6540
visitProperties @ lockdown.umd.js:8576
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
whitelistIntrinsics @ lockdown.umd.js:8605
repairIntrinsics @ lockdown.umd.js:8948
lockdown @ lockdown.umd.js:9025
(anonymous) @ bridge.html?suggestedDappPetname=FungibleFaucet:1
lockdown.umd.js:6540 Removing intrinsics.%ArrayPrototype%.toSpliced
warn @ lockdown.umd.js:6540
visitProperties @ lockdown.umd.js:8576
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
whitelistIntrinsics @ lockdown.umd.js:8605
repairIntrinsics @ lockdown.umd.js:8948
lockdown @ lockdown.umd.js:9025
(anonymous) @ bridge.html?suggestedDappPetname=FungibleFaucet:1
lockdown.umd.js:6540 Removing intrinsics.%ArrayPrototype%.with
warn @ lockdown.umd.js:6540
visitProperties @ lockdown.umd.js:8576
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
whitelistIntrinsics @ lockdown.umd.js:8605
repairIntrinsics @ lockdown.umd.js:8948
lockdown @ lockdown.umd.js:9025
(anonymous) @ bridge.html?suggestedDappPetname=FungibleFaucet:1
lockdown.umd.js:6540 Removing intrinsics.%ArrayPrototype%.@@unscopables.toReversed
warn @ lockdown.umd.js:6540
visitProperties @ lockdown.umd.js:8576
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
whitelistIntrinsics @ lockdown.umd.js:8605
repairIntrinsics @ lockdown.umd.js:8948
lockdown @ lockdown.umd.js:9025
(anonymous) @ bridge.html?suggestedDappPetname=FungibleFaucet:1
lockdown.umd.js:6540 Removing intrinsics.%ArrayPrototype%.@@unscopables.toSorted
warn @ lockdown.umd.js:6540
visitProperties @ lockdown.umd.js:8576
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
whitelistIntrinsics @ lockdown.umd.js:8605
repairIntrinsics @ lockdown.umd.js:8948
lockdown @ lockdown.umd.js:9025
(anonymous) @ bridge.html?suggestedDappPetname=FungibleFaucet:1
lockdown.umd.js:6540 Removing intrinsics.%ArrayPrototype%.@@unscopables.toSpliced
warn @ lockdown.umd.js:6540
visitProperties @ lockdown.umd.js:8576
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
whitelistIntrinsics @ lockdown.umd.js:8605
repairIntrinsics @ lockdown.umd.js:8948
lockdown @ lockdown.umd.js:9025
(anonymous) @ bridge.html?suggestedDappPetname=FungibleFaucet:1
lockdown.umd.js:6540 Removing intrinsics.%StringPrototype%.isWellFormed
warn @ lockdown.umd.js:6540
visitProperties @ lockdown.umd.js:8576
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
whitelistIntrinsics @ lockdown.umd.js:8605
repairIntrinsics @ lockdown.umd.js:8948
lockdown @ lockdown.umd.js:9025
(anonymous) @ bridge.html?suggestedDappPetname=FungibleFaucet:1
lockdown.umd.js:6540 Removing intrinsics.%StringPrototype%.toWellFormed
warn @ lockdown.umd.js:6540
visitProperties @ lockdown.umd.js:8576
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
whitelistIntrinsics @ lockdown.umd.js:8605
repairIntrinsics @ lockdown.umd.js:8948
lockdown @ lockdown.umd.js:9025
(anonymous) @ bridge.html?suggestedDappPetname=FungibleFaucet:1
lockdown.umd.js:6540 Removing intrinsics.%TypedArrayPrototype%.toReversed
warn @ lockdown.umd.js:6540
visitProperties @ lockdown.umd.js:8576
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
whitelistIntrinsics @ lockdown.umd.js:8605
repairIntrinsics @ lockdown.umd.js:8948
lockdown @ lockdown.umd.js:9025
(anonymous) @ bridge.html?suggestedDappPetname=FungibleFaucet:1
lockdown.umd.js:6540 Removing intrinsics.%TypedArrayPrototype%.toSorted
warn @ lockdown.umd.js:6540
visitProperties @ lockdown.umd.js:8576
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
whitelistIntrinsics @ lockdown.umd.js:8605
repairIntrinsics @ lockdown.umd.js:8948
lockdown @ lockdown.umd.js:9025
(anonymous) @ bridge.html?suggestedDappPetname=FungibleFaucet:1
lockdown.umd.js:6540 Removing intrinsics.%TypedArrayPrototype%.with
warn @ lockdown.umd.js:6540
visitProperties @ lockdown.umd.js:8576
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
whitelistIntrinsics @ lockdown.umd.js:8605
repairIntrinsics @ lockdown.umd.js:8948
lockdown @ lockdown.umd.js:9025
(anonymous) @ bridge.html?suggestedDappPetname=FungibleFaucet:1
lockdown.umd.js:6540 lockdown done.
lockdown.umd.js:6540 {connectionState: 'disconnected', schemaActions: null, services: null, setConnectionState: ƒ, setBackend: ƒ, …}
logo.svg:1  GET https://agoric.com/wp-content/themes/agoric_2021_theme/assets/img/logo.svg 404
Image (async)
z @ main.eed1f954.js:sourcemap:75
es @ main.eed1f954.js:sourcemap:75
vl @ main.eed1f954.js:sourcemap:75
ml @ main.eed1f954.js:sourcemap:75
hl @ main.eed1f954.js:sourcemap:75
sl @ main.eed1f954.js:sourcemap:75
nl @ main.eed1f954.js:sourcemap:75
Zl @ main.eed1f954.js:sourcemap:75
(anonymous) @ main.eed1f954.js:sourcemap:75
cl @ main.eed1f954.js:sourcemap:75
Yl @ main.eed1f954.js:sourcemap:75
t.render @ main.eed1f954.js:sourcemap:75
(anonymous) @ main.eed1f954.js:sourcemap:102
(anonymous) @ main.eed1f954.js:sourcemap:102
(anonymous) @ main.eed1f954.js:sourcemap:102
```

**Comment by dckc** [comment]
## not the wallet bridge

`http://localhost:8000/wallet/bridge.html?suggestedDappPetname=FungibleFaucet`

![image](https://user-images.githubusercontent.com/150986/230144694-9ce17493-ba32-425e-b6d2-9e31f3d9a70d.png)

**Comment by dckc** [comment]
cc @anilhelvaci

**Comment by anilhelvaci** [comment]
## Discovered New Behavior

I shared below error message yesterday

```
RangeError#1: Unexpected connect message type agoric_walletBridgeLoaded
logErrorInfo @ ses.umd.js:6589
ses.umd.js:6685   at makeError (http://localhost:3000/index.216c8fb4.js:1907:31)
  at fail (http://localhost:3000/index.216c8fb4.js:2005:36)
  at Function.equal (http://localhost:3000/index.216c8fb4.js:2018:45)
  at AgoricWalletConnection.onMessage (http://localhost:3000/index.216c8fb4.js:22673:29)
  at H.handleEvent (http://localhost:3000/index.216c8fb4.js:17288:52)
  at AgoricIframeMessenger._onMessage (http://localhost:3000/index.216c8fb4.js:22795:18)
```

What I discovered is that above error is thrown only when I block cookies for `https://wallet.agoric.app`

<img width="80%" alt="image" src="https://user-images.githubusercontent.com/32987478/230332348-36c61b9e-b224-411f-ab8a-3e82718f026a.png">

And the looping error in the issue title is thrown when I allow cookies for `https://wallet.agoric.app`

<img width="80%" alt="image" src="https://user-images.githubusercontent.com/32987478/230333955-3b8fb16a-5b46-466e-b68e-80a761645075.png">

```
locating locate CustomEvent {isTrusted: false, detail: {…}, type: 'message', target: agoric-iframe-messenger, currentTarget: agoric-iframe-messenger, …}
DevTools failed to load source map: Could not load content for chrome-extension://dmkamcknogkgcdfhhbddcghachkejeap/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
lockdown.umd.js:6540 Removing intrinsics.%ArrayPrototype%.toReversed
warn @ lockdown.umd.js:6540
visitProperties @ lockdown.umd.js:8576
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
whitelistIntrinsics @ lockdown.umd.js:8605
repairIntrinsics @ lockdown.umd.js:8948
lockdown @ lockdown.umd.js:9025
(anonymous) @ bridge.html:1
lockdown.umd.js:6540 Removing intrinsics.%ArrayPrototype%.toSorted
warn @ lockdown.umd.js:6540
visitProperties @ lockdown.umd.js:8576
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
whitelistIntrinsics @ lockdown.umd.js:8605
repairIntrinsics @ lockdown.umd.js:8948
lockdown @ lockdown.umd.js:9025
(anonymous) @ bridge.html:1
lockdown.umd.js:6540 Removing intrinsics.%ArrayPrototype%.toSpliced
warn @ lockdown.umd.js:6540
visitProperties @ lockdown.umd.js:8576
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
whitelistIntrinsics @ lockdown.umd.js:8605
repairIntrinsics @ lockdown.umd.js:8948
lockdown @ lockdown.umd.js:9025
(anonymous) @ bridge.html:1
lockdown.umd.js:6540 Removing intrinsics.%ArrayPrototype%.with
warn @ lockdown.umd.js:6540
visitProperties @ lockdown.umd.js:8576
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
whitelistIntrinsics @ lockdown.umd.js:8605
repairIntrinsics @ lockdown.umd.js:8948
lockdown @ lockdown.umd.js:9025
(anonymous) @ bridge.html:1
lockdown.umd.js:6540 Removing intrinsics.%ArrayPrototype%.@@unscopables.toReversed
warn @ lockdown.umd.js:6540
visitProperties @ lockdown.umd.js:8576
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
whitelistIntrinsics @ lockdown.umd.js:8605
repairIntrinsics @ lockdown.umd.js:8948
lockdown @ lockdown.umd.js:9025
(anonymous) @ bridge.html:1
lockdown.umd.js:6540 Removing intrinsics.%ArrayPrototype%.@@unscopables.toSorted
warn @ lockdown.umd.js:6540
visitProperties @ lockdown.umd.js:8576
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
whitelistIntrinsics @ lockdown.umd.js:8605
repairIntrinsics @ lockdown.umd.js:8948
lockdown @ lockdown.umd.js:9025
(anonymous) @ bridge.html:1
lockdown.umd.js:6540 Removing intrinsics.%ArrayPrototype%.@@unscopables.toSpliced
warn @ lockdown.umd.js:6540
visitProperties @ lockdown.umd.js:8576
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
whitelistIntrinsics @ lockdown.umd.js:8605
repairIntrinsics @ lockdown.umd.js:8948
lockdown @ lockdown.umd.js:9025
(anonymous) @ bridge.html:1
lockdown.umd.js:6540 Removing intrinsics.%StringPrototype%.isWellFormed
warn @ lockdown.umd.js:6540
visitProperties @ lockdown.umd.js:8576
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
whitelistIntrinsics @ lockdown.umd.js:8605
repairIntrinsics @ lockdown.umd.js:8948
lockdown @ lockdown.umd.js:9025
(anonymous) @ bridge.html:1
lockdown.umd.js:6540 Removing intrinsics.%StringPrototype%.toWellFormed
warn @ lockdown.umd.js:6540
visitProperties @ lockdown.umd.js:8576
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
whitelistIntrinsics @ lockdown.umd.js:8605
repairIntrinsics @ lockdown.umd.js:8948
lockdown @ lockdown.umd.js:9025
(anonymous) @ bridge.html:1
lockdown.umd.js:6540 Removing intrinsics.%TypedArrayPrototype%.toReversed
warn @ lockdown.umd.js:6540
visitProperties @ lockdown.umd.js:8576
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
whitelistIntrinsics @ lockdown.umd.js:8605
repairIntrinsics @ lockdown.umd.js:8948
lockdown @ lockdown.umd.js:9025
(anonymous) @ bridge.html:1
lockdown.umd.js:6540 Removing intrinsics.%TypedArrayPrototype%.toSorted
warn @ lockdown.umd.js:6540
visitProperties @ lockdown.umd.js:8576
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
whitelistIntrinsics @ lockdown.umd.js:8605
repairIntrinsics @ lockdown.umd.js:8948
lockdown @ lockdown.umd.js:9025
(anonymous) @ bridge.html:1
lockdown.umd.js:6540 Removing intrinsics.%TypedArrayPrototype%.with
warn @ lockdown.umd.js:6540
visitProperties @ lockdown.umd.js:8576
isAllowedPropertyValue @ lockdown.umd.js:8455
isAllowedProperty @ lockdown.umd.js:8515
visitProperties @ lockdown.umd.js:8562
whitelistIntrinsics @ lockdown.umd.js:8605
repairIntrinsics @ lockdown.umd.js:8948
lockdown @ lockdown.umd.js:9025
(anonymous) @ bridge.html:1
lockdown.umd.js:6540 lockdown done.
lockdown.umd.js:6540 {connectionState: 'disconnected', schemaActions: null, services: null, setConnectionState: ƒ, setBackend: ƒ, …}
lockdown.umd.js:6540 This package is deprecated. Use @agoric/web-components instead of @agoric/wallet-connection.
warn @ lockdown.umd.js:6540
689 @ 477.36027d30.chunk.js:32
__webpack_require__ @ main.eed1f954.js:75
Promise.then (async)
r @ main.eed1f954.js:102
o @ main.eed1f954.js:102
(anonymous) @ main.eed1f954.js:102
ls @ main.eed1f954.js:75
El @ main.eed1f954.js:75
t.unstable_runWithPriority @ main.eed1f954.js:75
Vo @ main.eed1f954.js:75
Cl @ main.eed1f954.js:75
sl @ main.eed1f954.js:75
(anonymous) @ main.eed1f954.js:75
t.unstable_runWithPriority @ main.eed1f954.js:75
Vo @ main.eed1f954.js:75
zo @ main.eed1f954.js:75
Yo @ main.eed1f954.js:75
cl @ main.eed1f954.js:75
Yl @ main.eed1f954.js:75
t.render @ main.eed1f954.js:75
(anonymous) @ main.eed1f954.js:102
(anonymous) @ main.eed1f954.js:102
(anonymous) @ main.eed1f954.js:102
logo.svg:1          GET https://agoric.com/wp-content/themes/agoric_2021_theme/assets/img/logo.svg 404
Image (async)
z @ VM3246 main.eed1f954.js:75
es @ VM3246 main.eed1f954.js:75
vl @ VM3246 main.eed1f954.js:75
ml @ VM3246 main.eed1f954.js:75
hl @ VM3246 main.eed1f954.js:75
sl @ VM3246 main.eed1f954.js:75
nl @ VM3246 main.eed1f954.js:75
Zl @ VM3246 main.eed1f954.js:75
(anonymous) @ VM3246 main.eed1f954.js:75
cl @ VM3246 main.eed1f954.js:75
Yl @ VM3246 main.eed1f954.js:75
t.render @ VM3246 main.eed1f954.js:75
(anonymous) @ VM3246 main.eed1f954.js:102
(anonymous) @ VM3246 main.eed1f954.js:102
(anonymous) @ VM3246 main.eed1f954.js:102
lockdown.umd.js:6540 {connectionState: 'locating', schemaActions: Promise, services: null, setConnectionState: ƒ, setBackend: ƒ, …}
lockdown.umd.js:6540 {connectionState: 'locating', schemaActions: Promise, services: {…}, setConnectionState: ƒ, setBackend: ƒ, …}
DevTools failed to load source map: Could not load content for chrome-extension://dmkamcknogkgcdfhhbddcghachkejeap/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
lockdown.umd.js:6540 locating locate CustomEvent {isTrusted: false, detail: {…}, type: 'message', target: agoric-iframe-messenger, currentTarget: agoric-iframe-messenger, …}
lockdown.umd.js:6540 {connectionState: 'bridged', schemaActions: Promise, services: {…}, setConnectionState: ƒ, setBackend: ƒ, …}
lockdown.umd.js:6540 {connectionState: 'bridged', schemaActions: Promise, services: {…}, setConnectionState: ƒ, setBackend: ƒ, …}
lockdown.umd.js:6540 {connectionState: 'bridged', schemaActions: Promise, services: {…}, setConnectionState: ƒ, setBackend: ƒ, …}
lockdown.umd.js:6540 {connectionState: 'bridged', schemaActions: Promise, services: {…}, setConnectionState: ƒ, setBackend: ƒ, …}
lockdown.umd.js:6540 {connectionState: 'bridged', schemaActions: Promise, services: {…}, setConnectionState: ƒ, setBackend: ƒ, …}
lockdown.umd.js:6540 {connectionState: 'bridged', schemaActions: Promise, services: {…}, setConnectionState: ƒ, setBackend: ƒ, …}
ses.umd.js:6702 connecting error CustomEvent {isTrusted: false, detail: {…}, type: 'error', target: agoric-iframe-messenger, currentTarget: agoric-iframe-messenger, …}
ses.umd.js:6702 error {state: 'error', walletConnection: Alleged: WalletConnection, cache: ƒ}
```
